language: node_js
branches:
  only:
  - master

node_js:
  - "7.0"

install:
  - npm install

script:
  - echo yolo tests later

notifications:
  slack:
    secure: iygUiicsZHkUaHC+zZoGMpdRzpZvGvsBm+eHvFt/dGOBZdhdVCAj2oTMECyDrHfCgWH8jvnhxT24U6vXAmTKXCf+Jqd3H3Of0hqUWAfb9RCaPoWcBaTfl45wz8lPbJ0ESU1Z0RP71laxG8clTzibeV4rJ3UwrxOonl/Bi0vpypX0vwQm9AwAWOZEcnwIYJFdoi1eKH+lDDBeCMiwQ8XEG3qnNvEMK3KRlQPwLvX895o1O1NSvcV4dbFbxn68pOlQN/15ILeQNSoaGWG7Akng/5elKhZBenO7R4VOcrSx22RW67EEoY5qfazSNyUzgdQT8EJ7ZetZZkpSEq5ex31GsIpamwJOzd4NKchh+rWvJZxThSPmzfZzGW33sZI6Buyq5i3Eddz5TOpSxZvNtmAITwil2d/JuLzfwOGjMfKYXd3WIAr1XHvCK7oN62hsfs6d2SlsN2uZ29zK8kBrMow2yhddW0xIqK1GQUXd0iiYK6Sle0UC7qpnWTj3mSnNAZcr/SxKFpMzr3UEIG5C8tgBfEmK7x6Fj2Gc3LTer0uCW2uFskc0etaKQ2O0KETnENsy4A7bfyJl++YyRmbKiZLg+UzCMCjuXUtH7XSH8X4IDLXZPldr0N0mfeUC2LdNOe8vkV5u8D8a1OxYV96MxNAcJ4s+bUhsmCERTMNyhBTMGx0=
